stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./rancher-lb/Dockerfile
      buildContext: ./rancher-lb
      tag: xkodiak/rancher-lb:latest
      registry: 127.0.0.1:34420
  - publishImageConfig:
      dockerfilePath: ./rancher-backup/Dockerfile
      buildContext: ./rancher-backup
      tag: xkodiak/rancher-backup:latest
      registry: 127.0.0.1:34420
timeout: 60
notification: {}
